default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.10.70:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.10.70:1880/
    require_admin: true
mqtt:
  broker: 192.168.10.70

recorder:
  db_url: mysql://homeassistant:mypassword@192.168.10.70/ha_db?charset=utf8
  purge_keep_days: 30
