# image: python:3.6
image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_TAG: "myflask:$CI_PROJECT_ID"

stages:
  - test
  - build
  - push
  - cleanup

build:
  stage: build
  script:
    - docker info
    - docker build -t "$IMAGE_TAG" .

test:
  image: python:3.6
  stage: test
  script:
    - export PYTHONPATH=/builds/xyj/fullstack_blog
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - cd blog_site/admin/test
    - echo $PYTHONPATH
    - python test.py

push:
  stage: push
  script:
    - docker login -u "xyj" -p "docker-registry" myregistry.com:8080
    - docker tag "$IMAGE_TAG" "myregistry.com:8080/myflask"
    - docker push "myregistry.com:8080/myflask"

cleanup:
  stage: cleanup
  script:
    - docker stop c-test-flask
    - docker rm c-test-flask
    - docker rmi "$IMAGE_TAG"